### ISSUE TITLE
Nginx with NFS => true didn't work for me

### ISSUE THREAD

**Issue by crimann** [mrimann/VagrantTYPO3Flow#1]
Couldn't get Nginx to work with :nfs => true.

**Comment by mchang89** [comment]
still having this issue:
```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'dmode=777,fmode=777' 192.168.42.1:'/Users/SERVER/vHosts' /var/www

# -*- mode: ruby -*-
Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: an incorrect mount option was specified
```

Changed 
```
config.vm.synced_folder "vHosts/", "/var/www/", :mount_options => ["dmode=777","fmode=777"], :nfs => true
```
to
```
config.vm.synced_folder "vHosts/", "/var/www/", :nfs => { :mount_options => ["dmode=777","fmode=777"] }
```

and it worked. Got the hint from this thread:

https://github.com/mitchellh/vagrant/issues/2546

Had some issues still connecting to mysql socket. I reinstalled mysql to get it to work. 
Tested on newest Vagrant Version and VM - MacOSX. 

Thx for this great box!

**Comment by mrimann** [comment]
@mchang89 I just checked and found out that I (locally) had a mount line in the Vagrantfile *without* any mount options at all, ... Thanks for pointing out the problem!

The line looks like the following (and I'll update the repo in a second):

`config.vm.synced_folder "vHosts/", "/var/www/", :nfs => true`

btw: could you send me some notes, for what and how you're using this box? I'm curious to see in which ways it's being used around the world :-)

**Comment by mchang89** [comment]
Thx for the update. 

I am using this Box for our Typo3 CMS Projects for our agency. I was looking for a simple out-of-the-box setup for our devs and this is by far the best box i have found with a LEMP Stack. I am thinking about using it for Magento and Shopware Projects too with an adjusted configuration. Cheers.

**Comment by mrimann** [comment]
Cool, thanks for the kind words!

Feel free to spread the word about it so others can use it, too. Or visit http://rimann.org/support for some inspiration (SCNR) :-)
